SIM ?= questa

MODULE ?= wishbone_loader_cocotb
TOPLEVEL=user_project_wrapper
TOPLEVEL_LANG?=verilog
FPGA_LIB = fpgalib
#RTL_LIBRARY = worklib

SIMSCRIPT = sim_build/runsim.do

COMPILE_ARGS = -2008 -suppress 1902 -suppress 2892 +define+UNIT_DELAY +define+FUNCTIONAL +define+USE_POWER_PINS
SIM_ARGS = -t 1ps
COCOTB_HDL_TIMEUNIT = 1ps
COCOTB_HDL_TIMEPRECISION = 1ps

BASEDIR ?= ../..

#VERILOG_SOURCES = $(BASEDIR)/rtl/tech/asic_skwt_130d/fpga_tech.v $(BASEDIR)/rtl/tech/asic_skwt_130d/models/primitives.v $(BASEDIR)/rtl/tech/asic_skwt_130d/models/sky130_fd_sc_hd.specify.v
VERILOG_SOURCES = $(BASEDIR)/rtl/tech/asic_skwt_130d/fpga_tech.v $(BASEDIR)/rtl/tech/asic_skwt_130d/models/primitives.v /home/anarky/fpga/rtl/tech/asic_skwt_130d/models/sky130_fd_sc_hd.specify.v fpga_struct_block.powered.v user_project_wrapper.powered.v


include $(shell cocotb-config --makefiles)/Makefile.sim
