SIM ?= questa

MODULE ?= wishbone_loader_cocotb
TOPLEVEL= user_project_wrapper
TOPLEVEL_LANG?=verilog
#RTL_LIBRARY = worklib

SIMSCRIPT = sim_build/runsim.do

COMPILE_ARGS = -2008 -suppress 1902 -suppress 2892 +define+UNIT_DELAY=\#1 +define+FUNCTIONAL
SIM_ARGS = -t 1ps
COCOTB_HDL_TIMEUNIT = 1ps
COCOTB_HDL_TIMEPRECISION = 1ps

BASEDIR ?= ../..

VERILOG_SOURCES = \
/home/anarky/gf180mcu_fd_sc_mcu7t5v0.v \
/home/anarky/gf180_efuse/macros/cells.v \
/home/anarky/gf180_efuse/macros/efuse_array.v \
/home/anarky/fpga_struct_block.nl.v \
/home/anarky/efuse_ctrl.nl.v \
/home/anarky/user_project_wrapper.nl.v
#VHDL_SOURCES = /home/anarky/gf180_efuse/hw/efuse_array.vhd

include $(shell cocotb-config --makefiles)/Makefile.sim
